version: '3.8'
services:
  postgres_db:
    image: postgres:13.5
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres_db:
    driver: local
