/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;

import vn.aivhub.data.tables.AccountVerifycation;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountVerifycationRecord extends TableRecordImpl<AccountVerifycationRecord> implements Record3<String, Integer, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account_verifycation.id</code>.
     */
    public AccountVerifycationRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.account_verifycation.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.account_verifycation.user_id</code>.
     */
    public AccountVerifycationRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.account_verifycation.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.account_verifycation.created_at</code>.
     */
    public AccountVerifycationRecord setCreatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.account_verifycation.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<String, Integer, LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<String, Integer, LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AccountVerifycation.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AccountVerifycation.USER_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return AccountVerifycation.CREATED_AT;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public AccountVerifycationRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public AccountVerifycationRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public AccountVerifycationRecord value3(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AccountVerifycationRecord values(String value1, Integer value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountVerifycationRecord
     */
    public AccountVerifycationRecord() {
        super(AccountVerifycation.ACCOUNT_VERIFYCATION);
    }

    /**
     * Create a detached, initialised AccountVerifycationRecord
     */
    public AccountVerifycationRecord(String id, Integer userId, LocalDateTime createdAt) {
        super(AccountVerifycation.ACCOUNT_VERIFYCATION);

        setId(id);
        setUserId(userId);
        setCreatedAt(createdAt);
    }
}
