/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import vn.aivhub.data.tables.BillingHistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BillingHistoryRecord extends UpdatableRecordImpl<BillingHistoryRecord> implements Record7<Integer, Integer, String, LocalDateTime, LocalDateTime, Double, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.billing_history.id</code>.
     */
    public BillingHistoryRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.billing_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.billing_history.plan_user_id</code>.
     */
    public BillingHistoryRecord setPlanUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.billing_history.plan_user_id</code>.
     */
    public Integer getPlanUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.billing_history.status</code>.
     */
    public BillingHistoryRecord setStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.billing_history.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.billing_history.created_at</code>.
     */
    public BillingHistoryRecord setCreatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.billing_history.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.billing_history.paid_at</code>.
     */
    public BillingHistoryRecord setPaidAt(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.billing_history.paid_at</code>.
     */
    public LocalDateTime getPaidAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.billing_history.amount</code>.
     */
    public BillingHistoryRecord setAmount(Double value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.billing_history.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>public.billing_history.session_id</code>.
     */
    public BillingHistoryRecord setSessionId(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.billing_history.session_id</code>.
     */
    public String getSessionId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, String, LocalDateTime, LocalDateTime, Double, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, String, LocalDateTime, LocalDateTime, Double, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BillingHistory.ID;
    }

    @Override
    public Field<Integer> field2() {
        return BillingHistory.PLAN_USER_ID;
    }

    @Override
    public Field<String> field3() {
        return BillingHistory.STATUS;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return BillingHistory.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return BillingHistory.PAID_AT;
    }

    @Override
    public Field<Double> field6() {
        return BillingHistory.AMOUNT;
    }

    @Override
    public Field<String> field7() {
        return BillingHistory.SESSION_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getPlanUserId();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component5() {
        return getPaidAt();
    }

    @Override
    public Double component6() {
        return getAmount();
    }

    @Override
    public String component7() {
        return getSessionId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getPlanUserId();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value5() {
        return getPaidAt();
    }

    @Override
    public Double value6() {
        return getAmount();
    }

    @Override
    public String value7() {
        return getSessionId();
    }

    @Override
    public BillingHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BillingHistoryRecord value2(Integer value) {
        setPlanUserId(value);
        return this;
    }

    @Override
    public BillingHistoryRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public BillingHistoryRecord value4(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public BillingHistoryRecord value5(LocalDateTime value) {
        setPaidAt(value);
        return this;
    }

    @Override
    public BillingHistoryRecord value6(Double value) {
        setAmount(value);
        return this;
    }

    @Override
    public BillingHistoryRecord value7(String value) {
        setSessionId(value);
        return this;
    }

    @Override
    public BillingHistoryRecord values(Integer value1, Integer value2, String value3, LocalDateTime value4, LocalDateTime value5, Double value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BillingHistoryRecord
     */
    public BillingHistoryRecord() {
        super(BillingHistory.BILLING_HISTORY);
    }

    /**
     * Create a detached, initialised BillingHistoryRecord
     */
    public BillingHistoryRecord(Integer id, Integer planUserId, String status, LocalDateTime createdAt, LocalDateTime paidAt, Double amount, String sessionId) {
        super(BillingHistory.BILLING_HISTORY);

        setId(id);
        setPlanUserId(planUserId);
        setStatus(status);
        setCreatedAt(createdAt);
        setPaidAt(paidAt);
        setAmount(amount);
        setSessionId(sessionId);
    }
}
