/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import vn.aivhub.data.tables.ChargePlan;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChargePlanRecord extends UpdatableRecordImpl<ChargePlanRecord> implements Record7<Integer, String, Integer, Integer, Double, String, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.charge_plan.id</code>.
     */
    public ChargePlanRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.charge_plan.name</code>.
     */
    public ChargePlanRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.charge_plan.team_size</code>.
     */
    public ChargePlanRecord setTeamSize(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.team_size</code>.
     */
    public Integer getTeamSize() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.charge_plan.project_size</code>.
     */
    public ChargePlanRecord setProjectSize(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.project_size</code>.
     */
    public Integer getProjectSize() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.charge_plan.storage</code>.
     */
    public ChargePlanRecord setStorage(Double value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.storage</code>.
     */
    public Double getStorage() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>public.charge_plan.support_type</code>.
     */
    public ChargePlanRecord setSupportType(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.support_type</code>.
     */
    public String getSupportType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.charge_plan.money</code>.
     */
    public ChargePlanRecord setMoney(Double value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.money</code>.
     */
    public Double getMoney() {
        return (Double) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, Integer, Integer, Double, String, Double> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, Integer, Integer, Double, String, Double> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ChargePlan.ID;
    }

    @Override
    public Field<String> field2() {
        return ChargePlan.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return ChargePlan.TEAM_SIZE;
    }

    @Override
    public Field<Integer> field4() {
        return ChargePlan.PROJECT_SIZE;
    }

    @Override
    public Field<Double> field5() {
        return ChargePlan.STORAGE;
    }

    @Override
    public Field<String> field6() {
        return ChargePlan.SUPPORT_TYPE;
    }

    @Override
    public Field<Double> field7() {
        return ChargePlan.MONEY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getTeamSize();
    }

    @Override
    public Integer component4() {
        return getProjectSize();
    }

    @Override
    public Double component5() {
        return getStorage();
    }

    @Override
    public String component6() {
        return getSupportType();
    }

    @Override
    public Double component7() {
        return getMoney();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getTeamSize();
    }

    @Override
    public Integer value4() {
        return getProjectSize();
    }

    @Override
    public Double value5() {
        return getStorage();
    }

    @Override
    public String value6() {
        return getSupportType();
    }

    @Override
    public Double value7() {
        return getMoney();
    }

    @Override
    public ChargePlanRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ChargePlanRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ChargePlanRecord value3(Integer value) {
        setTeamSize(value);
        return this;
    }

    @Override
    public ChargePlanRecord value4(Integer value) {
        setProjectSize(value);
        return this;
    }

    @Override
    public ChargePlanRecord value5(Double value) {
        setStorage(value);
        return this;
    }

    @Override
    public ChargePlanRecord value6(String value) {
        setSupportType(value);
        return this;
    }

    @Override
    public ChargePlanRecord value7(Double value) {
        setMoney(value);
        return this;
    }

    @Override
    public ChargePlanRecord values(Integer value1, String value2, Integer value3, Integer value4, Double value5, String value6, Double value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChargePlanRecord
     */
    public ChargePlanRecord() {
        super(ChargePlan.CHARGE_PLAN);
    }

    /**
     * Create a detached, initialised ChargePlanRecord
     */
    public ChargePlanRecord(Integer id, String name, Integer teamSize, Integer projectSize, Double storage, String supportType, Double money) {
        super(ChargePlan.CHARGE_PLAN);

        setId(id);
        setName(name);
        setTeamSize(teamSize);
        setProjectSize(projectSize);
        setStorage(storage);
        setSupportType(supportType);
        setMoney(money);
    }
}
