/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import vn.aivhub.data.tables.PlanUser;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanUserRecord extends UpdatableRecordImpl<PlanUserRecord> implements Record4<Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.plan_user.id</code>.
     */
    public PlanUserRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.plan_user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.plan_user.user_id</code>.
     */
    public PlanUserRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.plan_user.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.plan_user.plan_id</code>.
     */
    public PlanUserRecord setPlanId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.plan_user.plan_id</code>.
     */
    public Integer getPlanId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.plan_user.status</code>.
     */
    public PlanUserRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.plan_user.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PlanUser.ID;
    }

    @Override
    public Field<Integer> field2() {
        return PlanUser.USER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return PlanUser.PLAN_ID;
    }

    @Override
    public Field<String> field4() {
        return PlanUser.STATUS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public Integer component3() {
        return getPlanId();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public Integer value3() {
        return getPlanId();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public PlanUserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PlanUserRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public PlanUserRecord value3(Integer value) {
        setPlanId(value);
        return this;
    }

    @Override
    public PlanUserRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public PlanUserRecord values(Integer value1, Integer value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlanUserRecord
     */
    public PlanUserRecord() {
        super(PlanUser.PLAN_USER);
    }

    /**
     * Create a detached, initialised PlanUserRecord
     */
    public PlanUserRecord(Integer id, Integer userId, Integer planId, String status) {
        super(PlanUser.PLAN_USER);

        setId(id);
        setUserId(userId);
        setPlanId(planId);
        setStatus(status);
    }
}
