/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;

import vn.aivhub.data.tables.User;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record16<Integer, String, String, String, String, String, Boolean, Boolean, String, Boolean, String, Integer, Integer, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user.id</code>.
     */
    public UserRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.user.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.user.username</code>.
     */
    public UserRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user.password</code>.
     */
    public UserRecord setPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.user.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user.first_name</code>.
     */
    public UserRecord setFirstName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.user.last_name</code>.
     */
    public UserRecord setLastName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user.email</code>.
     */
    public UserRecord setEmail(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.user.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.user.enabled</code>.
     */
    public UserRecord setEnabled(Boolean value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.user.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.user.email_verified</code>.
     */
    public UserRecord setEmailVerified(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>public.user.email_verified</code>.
     */
    public Boolean getEmailVerified() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.user.role</code>. USER - ADMIN
     */
    public UserRecord setRole(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>public.user.role</code>. USER - ADMIN
     */
    public String getRole() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.user.is_admin</code>.
     */
    public UserRecord setIsAdmin(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>public.user.is_admin</code>.
     */
    public Boolean getIsAdmin() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.user.dept</code>.
     */
    public UserRecord setDept(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>public.user.dept</code>.
     */
    public String getDept() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.user.iat</code>.
     */
    public UserRecord setIat(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>public.user.iat</code>.
     */
    public Integer getIat() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.user.exp</code>.
     */
    public UserRecord setExp(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>public.user.exp</code>.
     */
    public Integer getExp() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.user.sub</code>.
     */
    public UserRecord setSub(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>public.user.sub</code>.
     */
    public String getSub() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.user.subscription_type</code>.
     */
    public UserRecord setSubscriptionType(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>public.user.subscription_type</code>.
     */
    public String getSubscriptionType() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.user.org_id</code>.
     */
    public UserRecord setOrgId(Integer value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>public.user.org_id</code>.
     */
    public Integer getOrgId() {
        return (Integer) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Integer, String, String, String, String, String, Boolean, Boolean, String, Boolean, String, Integer, Integer, String, String, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Integer, String, String, String, String, String, Boolean, Boolean, String, Boolean, String, Integer, Integer, String, String, Integer> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return User.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return User.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return User.LAST_NAME;
    }

    @Override
    public Field<String> field6() {
        return User.EMAIL;
    }

    @Override
    public Field<Boolean> field7() {
        return User.ENABLED;
    }

    @Override
    public Field<Boolean> field8() {
        return User.EMAIL_VERIFIED;
    }

    @Override
    public Field<String> field9() {
        return User.ROLE;
    }

    @Override
    public Field<Boolean> field10() {
        return User.IS_ADMIN;
    }

    @Override
    public Field<String> field11() {
        return User.DEPT;
    }

    @Override
    public Field<Integer> field12() {
        return User.IAT;
    }

    @Override
    public Field<Integer> field13() {
        return User.EXP;
    }

    @Override
    public Field<String> field14() {
        return User.SUB;
    }

    @Override
    public Field<String> field15() {
        return User.SUBSCRIPTION_TYPE;
    }

    @Override
    public Field<Integer> field16() {
        return User.ORG_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public Boolean component7() {
        return getEnabled();
    }

    @Override
    public Boolean component8() {
        return getEmailVerified();
    }

    @Override
    public String component9() {
        return getRole();
    }

    @Override
    public Boolean component10() {
        return getIsAdmin();
    }

    @Override
    public String component11() {
        return getDept();
    }

    @Override
    public Integer component12() {
        return getIat();
    }

    @Override
    public Integer component13() {
        return getExp();
    }

    @Override
    public String component14() {
        return getSub();
    }

    @Override
    public String component15() {
        return getSubscriptionType();
    }

    @Override
    public Integer component16() {
        return getOrgId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public Boolean value7() {
        return getEnabled();
    }

    @Override
    public Boolean value8() {
        return getEmailVerified();
    }

    @Override
    public String value9() {
        return getRole();
    }

    @Override
    public Boolean value10() {
        return getIsAdmin();
    }

    @Override
    public String value11() {
        return getDept();
    }

    @Override
    public Integer value12() {
        return getIat();
    }

    @Override
    public Integer value13() {
        return getExp();
    }

    @Override
    public String value14() {
        return getSub();
    }

    @Override
    public String value15() {
        return getSubscriptionType();
    }

    @Override
    public Integer value16() {
        return getOrgId();
    }

    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value7(Boolean value) {
        setEnabled(value);
        return this;
    }

    @Override
    public UserRecord value8(Boolean value) {
        setEmailVerified(value);
        return this;
    }

    @Override
    public UserRecord value9(String value) {
        setRole(value);
        return this;
    }

    @Override
    public UserRecord value10(Boolean value) {
        setIsAdmin(value);
        return this;
    }

    @Override
    public UserRecord value11(String value) {
        setDept(value);
        return this;
    }

    @Override
    public UserRecord value12(Integer value) {
        setIat(value);
        return this;
    }

    @Override
    public UserRecord value13(Integer value) {
        setExp(value);
        return this;
    }

    @Override
    public UserRecord value14(String value) {
        setSub(value);
        return this;
    }

    @Override
    public UserRecord value15(String value) {
        setSubscriptionType(value);
        return this;
    }

    @Override
    public UserRecord value16(Integer value) {
        setOrgId(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, Boolean value7, Boolean value8, String value9, Boolean value10, String value11, Integer value12, Integer value13, String value14, String value15, Integer value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, String username, String password, String firstName, String lastName, String email, Boolean enabled, Boolean emailVerified, String role, Boolean isAdmin, String dept, Integer iat, Integer exp, String sub, String subscriptionType, Integer orgId) {
        super(User.USER);

        setId(id);
        setUsername(username);
        setPassword(password);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setEnabled(enabled);
        setEmailVerified(emailVerified);
        setRole(role);
        setIsAdmin(isAdmin);
        setDept(dept);
        setIat(iat);
        setExp(exp);
        setSub(sub);
        setSubscriptionType(subscriptionType);
        setOrgId(orgId);
    }
}
