/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountVerifycation implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        id;
    private Integer       userId;
    private LocalDateTime createdAt;

    public AccountVerifycation() {}

    public AccountVerifycation(AccountVerifycation value) {
        this.id = value.id;
        this.userId = value.userId;
        this.createdAt = value.createdAt;
    }

    public AccountVerifycation(
        String        id,
        Integer       userId,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.userId = userId;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.account_verifycation.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.account_verifycation.id</code>.
     */
    public AccountVerifycation setId(String id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.account_verifycation.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.account_verifycation.user_id</code>.
     */
    public AccountVerifycation setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.account_verifycation.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.account_verifycation.created_at</code>.
     */
    public AccountVerifycation setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AccountVerifycation other = (AccountVerifycation) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountVerifycation (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
