/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChargePlan implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  name;
    private Integer teamSize;
    private Integer projectSize;
    private Double  storage;
    private String  supportType;
    private Double  money;

    public ChargePlan() {}

    public ChargePlan(ChargePlan value) {
        this.id = value.id;
        this.name = value.name;
        this.teamSize = value.teamSize;
        this.projectSize = value.projectSize;
        this.storage = value.storage;
        this.supportType = value.supportType;
        this.money = value.money;
    }

    public ChargePlan(
        Integer id,
        String  name,
        Integer teamSize,
        Integer projectSize,
        Double  storage,
        String  supportType,
        Double  money
    ) {
        this.id = id;
        this.name = name;
        this.teamSize = teamSize;
        this.projectSize = projectSize;
        this.storage = storage;
        this.supportType = supportType;
        this.money = money;
    }

    /**
     * Getter for <code>public.charge_plan.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.charge_plan.id</code>.
     */
    public ChargePlan setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.charge_plan.name</code>.
     */
    public ChargePlan setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.team_size</code>.
     */
    public Integer getTeamSize() {
        return this.teamSize;
    }

    /**
     * Setter for <code>public.charge_plan.team_size</code>.
     */
    public ChargePlan setTeamSize(Integer teamSize) {
        this.teamSize = teamSize;
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.project_size</code>.
     */
    public Integer getProjectSize() {
        return this.projectSize;
    }

    /**
     * Setter for <code>public.charge_plan.project_size</code>.
     */
    public ChargePlan setProjectSize(Integer projectSize) {
        this.projectSize = projectSize;
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.storage</code>.
     */
    public Double getStorage() {
        return this.storage;
    }

    /**
     * Setter for <code>public.charge_plan.storage</code>.
     */
    public ChargePlan setStorage(Double storage) {
        this.storage = storage;
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.support_type</code>.
     */
    public String getSupportType() {
        return this.supportType;
    }

    /**
     * Setter for <code>public.charge_plan.support_type</code>.
     */
    public ChargePlan setSupportType(String supportType) {
        this.supportType = supportType;
        return this;
    }

    /**
     * Getter for <code>public.charge_plan.money</code>.
     */
    public Double getMoney() {
        return this.money;
    }

    /**
     * Setter for <code>public.charge_plan.money</code>.
     */
    public ChargePlan setMoney(Double money) {
        this.money = money;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChargePlan other = (ChargePlan) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (teamSize == null) {
            if (other.teamSize != null)
                return false;
        }
        else if (!teamSize.equals(other.teamSize))
            return false;
        if (projectSize == null) {
            if (other.projectSize != null)
                return false;
        }
        else if (!projectSize.equals(other.projectSize))
            return false;
        if (storage == null) {
            if (other.storage != null)
                return false;
        }
        else if (!storage.equals(other.storage))
            return false;
        if (supportType == null) {
            if (other.supportType != null)
                return false;
        }
        else if (!supportType.equals(other.supportType))
            return false;
        if (money == null) {
            if (other.money != null)
                return false;
        }
        else if (!money.equals(other.money))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.teamSize == null) ? 0 : this.teamSize.hashCode());
        result = prime * result + ((this.projectSize == null) ? 0 : this.projectSize.hashCode());
        result = prime * result + ((this.storage == null) ? 0 : this.storage.hashCode());
        result = prime * result + ((this.supportType == null) ? 0 : this.supportType.hashCode());
        result = prime * result + ((this.money == null) ? 0 : this.money.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChargePlan (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(teamSize);
        sb.append(", ").append(projectSize);
        sb.append(", ").append(storage);
        sb.append(", ").append(supportType);
        sb.append(", ").append(money);

        sb.append(")");
        return sb.toString();
    }
}
