/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer userId;
    private Integer planId;
    private String  status;

    public PlanUser() {}

    public PlanUser(PlanUser value) {
        this.id = value.id;
        this.userId = value.userId;
        this.planId = value.planId;
        this.status = value.status;
    }

    public PlanUser(
        Integer id,
        Integer userId,
        Integer planId,
        String  status
    ) {
        this.id = id;
        this.userId = userId;
        this.planId = planId;
        this.status = status;
    }

    /**
     * Getter for <code>public.plan_user.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.plan_user.id</code>.
     */
    public PlanUser setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.plan_user.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.plan_user.user_id</code>.
     */
    public PlanUser setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.plan_user.plan_id</code>.
     */
    public Integer getPlanId() {
        return this.planId;
    }

    /**
     * Setter for <code>public.plan_user.plan_id</code>.
     */
    public PlanUser setPlanId(Integer planId) {
        this.planId = planId;
        return this;
    }

    /**
     * Getter for <code>public.plan_user.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>public.plan_user.status</code>.
     */
    public PlanUser setStatus(String status) {
        this.status = status;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlanUser other = (PlanUser) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (planId == null) {
            if (other.planId != null)
                return false;
        }
        else if (!planId.equals(other.planId))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.planId == null) ? 0 : this.planId.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlanUser (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(planId);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
