/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ResetPasswordToken implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       userId;
    private LocalDateTime createdAt;
    private LocalDateTime expirationTime;
    private String        token;

    public ResetPasswordToken() {}

    public ResetPasswordToken(ResetPasswordToken value) {
        this.id = value.id;
        this.userId = value.userId;
        this.createdAt = value.createdAt;
        this.expirationTime = value.expirationTime;
        this.token = value.token;
    }

    public ResetPasswordToken(
        Integer       id,
        Integer       userId,
        LocalDateTime createdAt,
        LocalDateTime expirationTime,
        String        token
    ) {
        this.id = id;
        this.userId = userId;
        this.createdAt = createdAt;
        this.expirationTime = expirationTime;
        this.token = token;
    }

    /**
     * Getter for <code>public.reset_password_token.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.reset_password_token.id</code>.
     */
    public ResetPasswordToken setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.reset_password_token.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.reset_password_token.user_id</code>.
     */
    public ResetPasswordToken setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>public.reset_password_token.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.reset_password_token.created_at</code>.
     */
    public ResetPasswordToken setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>public.reset_password_token.expiration_time</code>.
     */
    public LocalDateTime getExpirationTime() {
        return this.expirationTime;
    }

    /**
     * Setter for <code>public.reset_password_token.expiration_time</code>.
     */
    public ResetPasswordToken setExpirationTime(LocalDateTime expirationTime) {
        this.expirationTime = expirationTime;
        return this;
    }

    /**
     * Getter for <code>public.reset_password_token.token</code>.
     */
    public String getToken() {
        return this.token;
    }

    /**
     * Setter for <code>public.reset_password_token.token</code>.
     */
    public ResetPasswordToken setToken(String token) {
        this.token = token;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ResetPasswordToken other = (ResetPasswordToken) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        if (expirationTime == null) {
            if (other.expirationTime != null)
                return false;
        }
        else if (!expirationTime.equals(other.expirationTime))
            return false;
        if (token == null) {
            if (other.token != null)
                return false;
        }
        else if (!token.equals(other.token))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.expirationTime == null) ? 0 : this.expirationTime.hashCode());
        result = prime * result + ((this.token == null) ? 0 : this.token.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ResetPasswordToken (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(expirationTime);
        sb.append(", ").append(token);

        sb.append(")");
        return sb.toString();
    }
}
