/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  username;
    private String  password;
    private String  firstName;
    private String  lastName;
    private String  email;
    private Boolean enabled;
    private Boolean emailVerified;
    private String  role;
    private String  company;
    private Boolean isAdmin;
    private String  dept;
    private Integer iat;
    private Integer exp;
    private String  sub;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.email = value.email;
        this.enabled = value.enabled;
        this.emailVerified = value.emailVerified;
        this.role = value.role;
        this.company = value.company;
        this.isAdmin = value.isAdmin;
        this.dept = value.dept;
        this.iat = value.iat;
        this.exp = value.exp;
        this.sub = value.sub;
    }

    public User(
        Integer id,
        String  username,
        String  password,
        String  firstName,
        String  lastName,
        String  email,
        Boolean enabled,
        Boolean emailVerified,
        String  role,
        String  company,
        Boolean isAdmin,
        String  dept,
        Integer iat,
        Integer exp,
        String  sub
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.enabled = enabled;
        this.emailVerified = emailVerified;
        this.role = role;
        this.company = company;
        this.isAdmin = isAdmin;
        this.dept = dept;
        this.iat = iat;
        this.exp = exp;
        this.sub = sub;
    }

    /**
     * Getter for <code>public.user.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.user.id</code>.
     */
    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.user.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.user.username</code>.
     */
    public User setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>public.user.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.user.password</code>.
     */
    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.user.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>public.user.first_name</code>.
     */
    public User setFirstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * Getter for <code>public.user.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>public.user.last_name</code>.
     */
    public User setLastName(String lastName) {
        this.lastName = lastName;
        return this;
    }

    /**
     * Getter for <code>public.user.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.user.email</code>.
     */
    public User setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>public.user.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>public.user.enabled</code>.
     */
    public User setEnabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Getter for <code>public.user.email_verified</code>.
     */
    public Boolean getEmailVerified() {
        return this.emailVerified;
    }

    /**
     * Setter for <code>public.user.email_verified</code>.
     */
    public User setEmailVerified(Boolean emailVerified) {
        this.emailVerified = emailVerified;
        return this;
    }

    /**
     * Getter for <code>public.user.role</code>. USER - ADMIN
     */
    public String getRole() {
        return this.role;
    }

    /**
     * Setter for <code>public.user.role</code>. USER - ADMIN
     */
    public User setRole(String role) {
        this.role = role;
        return this;
    }

    /**
     * Getter for <code>public.user.company</code>.
     */
    public String getCompany() {
        return this.company;
    }

    /**
     * Setter for <code>public.user.company</code>.
     */
    public User setCompany(String company) {
        this.company = company;
        return this;
    }

    /**
     * Getter for <code>public.user.is_admin</code>.
     */
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    /**
     * Setter for <code>public.user.is_admin</code>.
     */
    public User setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
        return this;
    }

    /**
     * Getter for <code>public.user.dept</code>.
     */
    public String getDept() {
        return this.dept;
    }

    /**
     * Setter for <code>public.user.dept</code>.
     */
    public User setDept(String dept) {
        this.dept = dept;
        return this;
    }

    /**
     * Getter for <code>public.user.iat</code>.
     */
    public Integer getIat() {
        return this.iat;
    }

    /**
     * Setter for <code>public.user.iat</code>.
     */
    public User setIat(Integer iat) {
        this.iat = iat;
        return this;
    }

    /**
     * Getter for <code>public.user.exp</code>.
     */
    public Integer getExp() {
        return this.exp;
    }

    /**
     * Setter for <code>public.user.exp</code>.
     */
    public User setExp(Integer exp) {
        this.exp = exp;
        return this;
    }

    /**
     * Getter for <code>public.user.sub</code>.
     */
    public String getSub() {
        return this.sub;
    }

    /**
     * Setter for <code>public.user.sub</code>.
     */
    public User setSub(String sub) {
        this.sub = sub;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final User other = (User) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (username == null) {
            if (other.username != null)
                return false;
        }
        else if (!username.equals(other.username))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        if (firstName == null) {
            if (other.firstName != null)
                return false;
        }
        else if (!firstName.equals(other.firstName))
            return false;
        if (lastName == null) {
            if (other.lastName != null)
                return false;
        }
        else if (!lastName.equals(other.lastName))
            return false;
        if (email == null) {
            if (other.email != null)
                return false;
        }
        else if (!email.equals(other.email))
            return false;
        if (enabled == null) {
            if (other.enabled != null)
                return false;
        }
        else if (!enabled.equals(other.enabled))
            return false;
        if (emailVerified == null) {
            if (other.emailVerified != null)
                return false;
        }
        else if (!emailVerified.equals(other.emailVerified))
            return false;
        if (role == null) {
            if (other.role != null)
                return false;
        }
        else if (!role.equals(other.role))
            return false;
        if (company == null) {
            if (other.company != null)
                return false;
        }
        else if (!company.equals(other.company))
            return false;
        if (isAdmin == null) {
            if (other.isAdmin != null)
                return false;
        }
        else if (!isAdmin.equals(other.isAdmin))
            return false;
        if (dept == null) {
            if (other.dept != null)
                return false;
        }
        else if (!dept.equals(other.dept))
            return false;
        if (iat == null) {
            if (other.iat != null)
                return false;
        }
        else if (!iat.equals(other.iat))
            return false;
        if (exp == null) {
            if (other.exp != null)
                return false;
        }
        else if (!exp.equals(other.exp))
            return false;
        if (sub == null) {
            if (other.sub != null)
                return false;
        }
        else if (!sub.equals(other.sub))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.firstName == null) ? 0 : this.firstName.hashCode());
        result = prime * result + ((this.lastName == null) ? 0 : this.lastName.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.enabled == null) ? 0 : this.enabled.hashCode());
        result = prime * result + ((this.emailVerified == null) ? 0 : this.emailVerified.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        result = prime * result + ((this.company == null) ? 0 : this.company.hashCode());
        result = prime * result + ((this.isAdmin == null) ? 0 : this.isAdmin.hashCode());
        result = prime * result + ((this.dept == null) ? 0 : this.dept.hashCode());
        result = prime * result + ((this.iat == null) ? 0 : this.iat.hashCode());
        result = prime * result + ((this.exp == null) ? 0 : this.exp.hashCode());
        result = prime * result + ((this.sub == null) ? 0 : this.sub.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(email);
        sb.append(", ").append(enabled);
        sb.append(", ").append(emailVerified);
        sb.append(", ").append(role);
        sb.append(", ").append(company);
        sb.append(", ").append(isAdmin);
        sb.append(", ").append(dept);
        sb.append(", ").append(iat);
        sb.append(", ").append(exp);
        sb.append(", ").append(sub);

        sb.append(")");
        return sb.toString();
    }
}
