/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import vn.aivhub.data.tables.AccountVerifycation;
import vn.aivhub.data.tables.BillingHistory;
import vn.aivhub.data.tables.ChargePlan;
import vn.aivhub.data.tables.OauthToken;
import vn.aivhub.data.tables.Organization;
import vn.aivhub.data.tables.PlanUser;
import vn.aivhub.data.tables.ResetPasswordToken;
import vn.aivhub.data.tables.User;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account_verifycation</code>.
     */
    public final AccountVerifycation ACCOUNT_VERIFYCATION = AccountVerifycation.ACCOUNT_VERIFYCATION;

    /**
     * The table <code>public.billing_history</code>.
     */
    public final BillingHistory BILLING_HISTORY = BillingHistory.BILLING_HISTORY;

    /**
     * The table <code>public.charge_plan</code>.
     */
    public final ChargePlan CHARGE_PLAN = ChargePlan.CHARGE_PLAN;

    /**
     * The table <code>public.oauth_token</code>.
     */
    public final OauthToken OAUTH_TOKEN = OauthToken.OAUTH_TOKEN;

    /**
     * The table <code>public.organization</code>.
     */
    public final Organization ORGANIZATION = Organization.ORGANIZATION;

    /**
     * The table <code>public.plan_user</code>.
     */
    public final PlanUser PLAN_USER = PlanUser.PLAN_USER;

    /**
     * The table <code>public.reset_password_token</code>.
     */
    public final ResetPasswordToken RESET_PASSWORD_TOKEN = ResetPasswordToken.RESET_PASSWORD_TOKEN;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.BILLING_HISTORY_ID_SEQ,
            Sequences.CHARGE_PLAN_ID_SEQ,
            Sequences.OAUTH_TOKEN_ID_SEQ,
            Sequences.ORGANIZATION_ID_SEQ,
            Sequences.PLAN_USER_ID_SEQ,
            Sequences.RESET_PASSWORD_TOKEN_ID_SEQ,
            Sequences.USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            AccountVerifycation.ACCOUNT_VERIFYCATION,
            BillingHistory.BILLING_HISTORY,
            ChargePlan.CHARGE_PLAN,
            OauthToken.OAUTH_TOKEN,
            Organization.ORGANIZATION,
            PlanUser.PLAN_USER,
            ResetPasswordToken.RESET_PASSWORD_TOKEN,
            User.USER);
    }
}
