/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.billing_history_id_seq</code>
     */
    public static final Sequence<Integer> BILLING_HISTORY_ID_SEQ = Internal.createSequence("billing_history_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.charge_plan_id_seq</code>
     */
    public static final Sequence<Integer> CHARGE_PLAN_ID_SEQ = Internal.createSequence("charge_plan_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.oauth_token_id_seq</code>
     */
    public static final Sequence<Integer> OAUTH_TOKEN_ID_SEQ = Internal.createSequence("oauth_token_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.plan_user_id_seq</code>
     */
    public static final Sequence<Integer> PLAN_USER_ID_SEQ = Internal.createSequence("plan_user_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.reset_password_token_id_seq</code>
     */
    public static final Sequence<Integer> RESET_PASSWORD_TOKEN_ID_SEQ = Internal.createSequence("reset_password_token_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>public.user_id_seq</code>
     */
    public static final Sequence<Integer> USER_ID_SEQ = Internal.createSequence("user_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
