/*
 * This file is generated by jOOQ.
 */
package vn.aivhub.data;


import vn.aivhub.data.tables.AccountVerifycation;
import vn.aivhub.data.tables.BillingHistory;
import vn.aivhub.data.tables.ChargePlan;
import vn.aivhub.data.tables.OauthToken;
import vn.aivhub.data.tables.Organization;
import vn.aivhub.data.tables.PlanUser;
import vn.aivhub.data.tables.ResetPasswordToken;
import vn.aivhub.data.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account_verifycation</code>.
     */
    public static final AccountVerifycation ACCOUNT_VERIFYCATION = AccountVerifycation.ACCOUNT_VERIFYCATION;

    /**
     * The table <code>public.billing_history</code>.
     */
    public static final BillingHistory BILLING_HISTORY = BillingHistory.BILLING_HISTORY;

    /**
     * The table <code>public.charge_plan</code>.
     */
    public static final ChargePlan CHARGE_PLAN = ChargePlan.CHARGE_PLAN;

    /**
     * The table <code>public.oauth_token</code>.
     */
    public static final OauthToken OAUTH_TOKEN = OauthToken.OAUTH_TOKEN;

    /**
     * The table <code>public.organization</code>.
     */
    public static final Organization ORGANIZATION = Organization.ORGANIZATION;

    /**
     * The table <code>public.plan_user</code>.
     */
    public static final PlanUser PLAN_USER = PlanUser.PLAN_USER;

    /**
     * The table <code>public.reset_password_token</code>.
     */
    public static final ResetPasswordToken RESET_PASSWORD_TOKEN = ResetPasswordToken.RESET_PASSWORD_TOKEN;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
